// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5hcXucFLbU2HXXyViGsKcc
// Component: NwRWbWBeNPq
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_starter_blog.module.css" // plasmic-import: 5hcXucFLbU2HXXyViGsKcc/projectcss
import * as sty from "./PlasmicAuthorBio.module.css" // plasmic-import: NwRWbWBeNPq/css
import PlasmicLogoIcon from "./icons/PlasmicIcon__PlasmicLogo" // plasmic-import: Ay7G9ywA1AI/icon

export const PlasmicAuthorBio__VariantProps = new Array()

export const PlasmicAuthorBio__ArgProps = new Array("profilepic", "description")

function PlasmicAuthorBio__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <PlasmicLogoIcon
            className={classNames(defaultcss.all, sty.svg__k8SYh)}
            role={"img"}
          />
        ),

        value: args.profilepic,
      })}

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Built with love by the Plasmic team. ",
          value: args.description,
        })}
      </div>
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAuthorBio__ArgProps,
      internalVariantPropNames: PlasmicAuthorBio__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicAuthorBio__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicAuthorBio"
  } else {
    func.displayName = `PlasmicAuthorBio.${nodeName}`
  }
  return func
}

export const PlasmicAuthorBio = Object.assign(
  // Top-level PlasmicAuthorBio renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicAuthorBio
    internalVariantProps: PlasmicAuthorBio__VariantProps,
    internalArgProps: PlasmicAuthorBio__ArgProps,
  }
)

export default PlasmicAuthorBio
/* prettier-ignore-end */
