// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5hcXucFLbU2HXXyViGsKcc
// Component: zp7ZfI7ZOmd
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_starter_blog.module.css" // plasmic-import: 5hcXucFLbU2HXXyViGsKcc/projectcss
import * as sty from "./PlasmicPostHeader.module.css" // plasmic-import: zp7ZfI7ZOmd/css

export const PlasmicPostHeader__VariantProps = new Array()

export const PlasmicPostHeader__ArgProps = new Array(
  "postTitle",
  "date",
  "blogTitle"
)

function PlasmicPostHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(defaultcss.all, sty.link)}
        component={Link}
        href={"/"}
        platform={"gatsby"}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Plasmic Starter Blog",
          value: args.blogTitle,
          className: classNames(sty.slotBlogTitle),
        })}
      </p.PlasmicLink>

      {p.renderPlasmicSlot({
        defaultContents: "Hello world",
        value: args.postTitle,
        className: classNames(sty.slotPostTitle),
      })}

      {p.renderPlasmicSlot({
        defaultContents: "January 1, 2020",
        value: args.date,
        className: classNames(sty.slotDate),
      })}
    </div>
  )
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPostHeader__ArgProps,
      internalVariantPropNames: PlasmicPostHeader__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicPostHeader__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicPostHeader"
  } else {
    func.displayName = `PlasmicPostHeader.${nodeName}`
  }
  return func
}

export const PlasmicPostHeader = Object.assign(
  // Top-level PlasmicPostHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicPostHeader
    internalVariantProps: PlasmicPostHeader__VariantProps,
    internalArgProps: PlasmicPostHeader__ArgProps,
  }
)

export default PlasmicPostHeader
/* prettier-ignore-end */
